spring:
  application:
    name: ac-ai-code-free-backend
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ac_ai_code_free
    username: root
    password: 123456

server:
  port: 8700
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.adcage.acaicodefree.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

