spring:
  application:
    name: ac-ai-code-free-backend
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ac_ai_code_free
    username: root
    password: 123456
  profiles:
    active: local #使用local本地环境


server:
  port: 8700
  servlet:
    context-path: /api
    session:
      timeout: 1d

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.adcage.acaicodefree.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <your-api-key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json
      strict-json-schema: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <your-api-key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json